# Generated by Django 3.2.15 on 2022-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('story', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('mood', models.CharField(choices=[('happy', 'happy'), ('numb', 'numb'), ('angry', 'angry')], default='numb', max_length=15)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
